import { getPublicEntrySlug } from "../i18n/ui";
import { decodeSlugSafely, slugifyAscii } from "./slugify";

/**
 * Known public post URLs generated by the old slugifier. Keep this map as a
 * redirect contract so existing links remain valid after canonicalization.
 */
export const legacyPostSlugRedirects = {
  "cong-nghe-san-xuat-hien-ai-tai-thai-son-plastic":
    "cong-nghe-san-xuat-hien-dai-tai-thai-son-plastic",
  "bang-dinh-sieu-chac-la-gi-cau-tao-ac-iem-va-ung-dung":
    "bang-dinh-sieu-chac-la-gi-cau-tao-dac-diem-va-ung-dung",
} as const;

const legacyPostSlugs = new Set(Object.keys(legacyPostSlugRedirects));

export function canonicalizePostSlug(value: string): string {
  const decoded = decodeSlugSafely(value);
  const knownRedirect =
    legacyPostSlugRedirects[decoded as keyof typeof legacyPostSlugRedirects];

  return knownRedirect ?? slugifyAscii(decoded);
}

export function isLegacyPostSlug(value: string): boolean {
  return legacyPostSlugs.has(decodeSlugSafely(value));
}

export function getCanonicalPostSlug(entry: { id: string; data: { slug?: string | null } }): string {
  const contentSlug = entry.data.slug?.trim();
  return canonicalizePostSlug(contentSlug || getPublicEntrySlug(entry));
}
